# Generated by Django 5.1.2 on 2024-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='url',
            field=models.CharField(default='default-url', max_length=200),
        ),
    ]
