# Generated by Django 5.1.2 on 2024-10-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Question',
            new_name='question',
        ),
    ]
